Javítás elkészült
Hibaüzenet:
TypeError: 'str' object does not support item assignment
A user_info.py 7. pontja: a lista elemeinek felcserélése miatt.

Javítás:
Egy átmeneti változóval (temp) lett megoldva a korábbi típusbaki (TypeError) után.